//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playground.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Playground.Resources.AppStringResources", typeof(AppStringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string warmup_tee_drill {
            get {
                return ResourceManager.GetString("warmup_tee_drill", resourceCulture);
            }
        }
        
        public static string indoor_outdoor {
            get {
                return ResourceManager.GetString("indoor_outdoor", resourceCulture);
            }
        }
        
        public static string warmup_tee_drill_description {
            get {
                return ResourceManager.GetString("warmup_tee_drill_description", resourceCulture);
            }
        }
        
        public static string warmup_bread_basket {
            get {
                return ResourceManager.GetString("warmup_bread_basket", resourceCulture);
            }
        }
        
        public static string warmup_bread_basket_description {
            get {
                return ResourceManager.GetString("warmup_bread_basket_description", resourceCulture);
            }
        }
        
        public static string login_password_hint {
            get {
                return ResourceManager.GetString("login_password_hint", resourceCulture);
            }
        }
    }
}
